config/routes.rb
Rails.application.routes.draw do
  resources :bands
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  get '/cart/checkout' => 'cart#checkout', as: :checkout
  get '/cart/:id' => 'cart#add', as: :add_to_cart

  devise_for :users
  resources :vendors
  resources :events do 
    resources :show_times
    collection do
      get :past
      get :upcoming
      get :calendar
      get :attending
      get :all, action: :index
    end
  end
  resource :transaction

  get 'home' => 'home#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'videos' => 'home#videos'
  get 'fall' => 'home#fall'
  get 'loco' => 'home#loco'
  get 'mongo' => 'home#mongo'
  get 'donate' => 'home#donate'
  get 'info' => 'home#info'

  root 'home#index'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  name       :string
#  start_date :datetime
#  end_date   :datetime
#  address    :string
#  city       :string
#  state      :string
#  zipcode    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  price      :float
#

class Event < ActiveRecord::Base
    has_many :purchases
    has_many :buyers, through: :purchases
    has_many :show_times
    has_many :bands, through: :show_times
    include ArelHelpers::ArelTable
    scope :past, -> { Event.where(Event[:end_date].lteq(Date.yesterday))}
    scope :starting_after, ->(time) { where("start_date >= ?", time) }
    scope :ending_before, ->(time) { where("end_date <= ?", time) }
    scope :upcoming, -> { Event.where(Event[:start_date].gteq(Date.today))}
    
    def start_time
        self.start_date
    end
    
    def self.now
        self.starting_after(Time.now.beginning_of_day).ending_before(Time.now.beginning_of_day)
    end
    
    def occurring_on
       start_date.to_datetime..end_date.to_datetime
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end
  
  def upcoming
    @events = Event.upcoming
    render action: :index
  end
  
  def past
    @events = Event.past
    render action: :index
  end
  
  def attending
    if user_signed_in?
      @events = current_user.events.all
    else
      @events = Event.none
    end
    render action: :index
  end
  
  def calendar
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    # start_date = @event.start_date
    @date_range = @event.occurring_on.to_a
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_date, :end_date, :address, :city, :state, :zipcode, :price)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_calendar.html.erb
  <%= month_calendar events: events do |date, events| %>
    <%= date.stamp("7/8") %>
  
    <% events.each do |event| %>
      <div>
        <%= link_to event.name, event %>
      </div>
    <% end %>
  <% end %>

app/views/events/_event.html.erb
<%= div_for event do %>
<h2><%= link_to event.name, event %></h2>
<p><%= event.start_date.stamp("Mon, Aug 1st, 2016") %> - <%= event.end_date.stamp("Mon, Aug 1st, 2016")  %></p>

<% end %>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :name %><br>
  </div>
  <div class="field">
    <%= f.input :start_date %><br>
  </div>
  <div class="field">
    <%= f.input :end_date %><br>
  </div>
  <div class="field">
    <%= f.input :address %><br>
  </div>
  <div class="field">
    <%= f.input :city %><br>
  </div>
  <div class="field">
    <%= f.input :state %><br>
  </div>
  <div class="field">
    <%= f.input :zipcode %><br>
  </div>
  <div class="field">
    <%= f.input :price %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_table.html.erb
<table class="table table-bordered table-hover">
<thead>
  <tr>
    <th>Name</th>
    <th>Dates</th>
    <th>Price</th>
    <th></th>
  </tr>
</thead>

<tbody>
  <% events.each do |event| %>
    <tr>
      <td><%= link_to event.name, event %></td>
      <td><%= event.start_date.stamp("Aug 5th") %> - <%= event.end_date.stamp("Aug 5th") %></td>
      <td><%= number_to_currency event.price %></td>
      <td><%= link_to "Add To Cart", add_to_cart_path(event.id), class: "btn btn-info" %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/events/calendar.html.erb
<div class="col-md-12 light padd">
    <div class="well">
        <%= render "events/calendar", events: @events %>
    </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="col-md-12 light">
  <h1>Events</h1>
  <%= link_to "All Events", events_path, class: "btn btn-info btn-lg" %>
  <%= link_to "Past Events", past_events_path, class: "btn btn-default btn-lg" %>
  <%= link_to "Upcoming Events", upcoming_events_path, class: "btn btn-info btn-lg" %>
  <%= link_to "Events I'm Attending", attending_events_path, class: "btn btn-success btn-lg" %>
  <%= link_to "Calendar", calendar_events_path, class: "btn btn-info btn-lg" %>

  <hr>
  
<div class="well">
  <%= render "events/table", events: @events %>
</div>
  
  <hr>
  
  <%= link_to 'New Event', new_event_path %>

</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<div class="well"><%= render "form" %></div>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="col-md-12 light padd">
  
  <hr>
  <hr>
  <hr>
  
  <%= link_to "Show Times", event_show_times_path(@event)%>
  
  <hr>
  <h1>Line Up</h1>
  <% @event.show_times.each do |show_time| %>

    <h2><%= show_time.band.name %></h2>
<p><%= show_time.start_time.stamp("11:34 AM") %> - <%= show_time.end_time.stamp("11:34 AM") %><br>
</p>

  <% end %>
  <hr>
  
  
  <% @event_days = @event.occurring_on.map(&:to_datetime) %>

<%= week_calendar attribute: :to_datetime, events: @event_days do |date, event_days| %>
  <p class="big"><strong><%= date.stamp("8/1") %></strong></p>
  

  <% event_days.each do |event| %>
    <div>
      <%= event.name %>
      
        
    </div>
  <% end %>
<% end %>
<hr>
<%= link_to "Add To Cart", add_to_cart_path(@event.id), class: "btn btn-info btn-lg" %>
<hr>
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>
<div>
</div>
<hr>
<p>
  <strong>Start date:</strong>
  <%= @event.start_date.stamp("Aug 5th, 2016") %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date.stamp("Aug 5th, 2016") %>
</p>

<h3><%= @event.address %><br><%= @event.city %>, <%= @event.state %> <%= @event.zipcode %></h3>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @event.price %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', @event_days_path %>
<%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>