config/routes.rb
Rails.application.routes.draw do
  resources :bands
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  get '/cart/checkout' => 'cart#checkout', as: :checkout
  get '/cart/:id' => 'cart#add', as: :add_to_cart

  devise_for :users
  resources :vendors
  resources :events do 
    resources :show_times
    collection do
      get :past
      get :upcoming
      get :calendar
      get :attending
      get :all, action: :index
    end
  end
  resource :transaction

  get 'home' => 'home#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'videos' => 'home#videos'
  get 'fall' => 'home#fall'
  get 'loco' => 'home#loco'
  get 'mongo' => 'home#mongo'
  get 'donate' => 'home#donate'
  get 'info' => 'home#info'

  root 'home#index'

end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id           :integer          not null, primary key
#  name         :string
#  phone_number :string
#  contact_name :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Band < ActiveRecord::Base
    has_many :show_times
    # has_many :events, through: :show_times
    
    
    def playing_on
       show_times.map(&:occurring_on)
    end
    # def dates
    #     arr = []
    #     show_times.each do |show_time|
    #         t = show_time.start_time..show_time.end_time
    #       arr << t
    #     end
    #     arr
    # end
    
    # def playing_on?(date)
    #     dates.include?(date)
    # end
    
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :phone_number, :contact_name)
    end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= simple_form_for(@band) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :phone_number %>
    <%= f.input :contact_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Contact name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.name %></td>
        <td><%= band.phone_number %></td>
        <td><%= band.contact_name %></td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @band.phone_number %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @band.contact_name %>
</p>

<% @band.show_times.each do |set| %>
  <%= set.start_time %><br>
<% end %>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>