config/routes.rb
Rails.application.routes.draw do
  resources :bands
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  get '/cart/checkout' => 'cart#checkout', as: :checkout
  get '/cart/:id' => 'cart#add', as: :add_to_cart

  devise_for :users
  resources :vendors
  resources :events do 
    resources :show_times
    collection do
      get :past
      get :upcoming
      get :calendar
      get :attending
      get :all, action: :index
    end
  end
  resource :transaction

  get 'home' => 'home#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'videos' => 'home#videos'
  get 'fall' => 'home#fall'
  get 'loco' => 'home#loco'
  get 'mongo' => 'home#mongo'
  get 'donate' => 'home#donate'
  get 'info' => 'home#info'

  root 'home#index'

end

app/models/vendor.rb
# == Schema Information
#
# Table name: vendors
#
#  id           :integer          not null, primary key
#  name         :string
#  description  :text
#  phone_number :string
#  website      :string
#  contact_name :string
#  tagline      :string
#  category     :string
#  approved_at  :datetime
#  approved_by  :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Vendor < ActiveRecord::Base
    scope :approved, -> { where.not(approved_at: nil) }
    
    def approver(user_id)
        User.find(user_id)
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.approved
    @cart = cart
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name, :description, :phone_number, :website, :contact_name, :tagline, :category, :approved_at, :approved_by)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<div class="col-md-12 light padd">
  <%= simple_form_for(@vendor) do |f| %>
    <%= f.error_notification %>
  
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :phone_number %>
      <%= f.input :website %>
      <%= f.input :contact_name %>
      <%= f.input :tagline %>
      <%= f.input :category %>
      <%= f.input :approved_at %>
      <%= f.input :approved_by %>
    </div>
  
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/vendors/_table.html.erb
<div class='col-md-12 well'>
     <h1 class="text-center">VENDOR LIST</h1>
     <hr>
     <div class="table-responsive">
        <table class='table table-bordered table-hover'>
          <thead>
            <tr>
              <th>Name</th>
              <th>Phone number</th>
              <th>Website</th>
              <th>Contact name</th>
              <th>Tagline</th>
              <th>Category</th>
              <th>Approved at</th>
              <th>Approved by</th>
              <th>Admin</th>
            </tr>
          </thead>
        
          <tbody>
            <% vendors.each do |vendor| %>
              <tr>
                <td><%= link_to vendor.name, vendor, data: {target: "_blank"} %></td>
                <td><%= vendor.phone_number %></td>
                <td><%= link_to vendor.website, vendor.website if vendor.approved_at? %></td>
                <td><%= vendor.contact_name %></td>
                <td><%= vendor.tagline %></td>
                <td><%= vendor.category %></td>
                <td><%= vendor.approved_at %></td>
                <td><%= user_signed_in? ? vendor.approver(current_user.id) : "SIGN IN" %></td>
                <td><%= link_to 'Edit', edit_vendor_path(vendor) %> | <%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<div class="col-md-12 light padd">
<h1 class="page-header text-center">Vendors</h1>
<hr>
<div class="col-md-3">
  <%= vendor_placeholders(8) %>
</div>
<div class="col-md-6 light padd">
  <div class="vendor-info">
    <h1>How Can Your Business Get Noticed And Help Our Cause?</h1>
    <p class="lead">
      SPONSORSHIPS (tier level page included) will bring awareness and 
      promote your business in and around our community.
    </p>
    <p class="bold">
      **We invite you to provide business cards and flyers to us that will then be displayed at the event for all participants to view and collect.
      We are also accepting donations for raffles & or you can donate drectly to our generosity link:
      http://www.generosity.com/fundraisers/help-support-lorain-county-music-
      fest-10/generosity
    </p>
    
    
    <hr>
    <blockquote>**Thank you for your time & consideration of becoming a Local Music Supporter & a Lorain 
    County Music Fest donor/sponsor.*</blockquote>
    
    <hr>
    <h2>PLATINUM <small>Music Fest Sponsor </small> <span class="text-success pull-right"> $500.00 </span></h2> 
    <hr>
    <p>
     A sponsorship at this level will have their business logo listed on the event poster & flyer, 
    in any media advertising such as newspapers & social media or internet banners, & the main stage event banner. 
    <br>You will receive a Lo. Co. Music Fest Sponsor T-Shirt & passes to the 10 year event. 
    <br>You are also entitled to a 5X5 table space at our Winter Fest event to collect a mailing list and hand out samples of your product or service.
    </p>
    
    <hr>
    <h2>GOLD <small>Live Music Supporter </small> <span class="text-success pull-right"> $250.00 </span></h2> 
    
    <p>A sponsorship at this level will have their business logo listed on 
    the event poster & flyer, in any media advertising such as newspapers 
    & social media or internet banners, & the main stage event banner. <br>
    You will receive passes to the 10 year event. & are also entitled to a 5x5 table space to collect a mailing list & hand out samples of your product or service.</p>
    
    <hr>
    <h2>SILVER <small>Rock N Roller </small> <span class="text-success pull-right"> $100.00 </span></h2> 
    <p>
    A sponsorship at this level will have their business logo listed on 
    the event poster and flyer, in any media advertising such as newspapers 
    & social media or internet banners. </p>
    
    <hr>
    <h2>BRONZE <small>Music Lover </small> <span class="text-success pull-right"> $50.00 </span></h2> 
     
    <p>A sponsorship at this level will be allowed to display their business cards or flyers on our general event table.</p>
    
    <hr>
    <hr>
    *Please note that you are not required to represent your business in a 5x5 booth at the event; it is optional to you. If you wish to attend, please contact Geri Ciacchi, LCMF Public Relations Director, 
    at (440) 654-7000 or locomusicfest@yahoo.com as soon as possible so that she may send you a vendor application and assign you a space. If you cannot attend but wish to have information or promotional items displayed at the event, please send them directly to Geri Ciacchi 15407 Avon Belden Road, Grafton, Ohio 44044. You must be 18 or older to attend this event.
    <hr>
    <hr>
    <hr>
  </div>
</div>
<div class="col-md-3">
  <h3 class="text-center">Other Info</h3>
  <blockquote>
      If you would like a donation receipt for tax purposes, please let us know. 
    Should you have any questions regarding our event or donations of goods &/or services, please feel free to contact me. 
    I would be more than happy to talk to you about how your business can be involved.
    </blockquote>
    <hr>
    <%= vendor_placeholders(8) %>
</div>
<hr>
<h1>ADMIN</h1>
<hr>
  <div class="col-md-12">
    <hr>
  <%= render "vendors/table", vendors: @vendors %>
  </div>
  

</div>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<div class="col-md-12 light padd">

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vendor.description %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @vendor.phone_number %>
</p>

<p>
  <strong>Website:</strong>
  <%= link_to @vendor.website, @vendor.website %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @vendor.contact_name %>
</p>

<p>
  <strong>Tagline:</strong>
  <%= @vendor.tagline %>
</p>

<p>
  <strong>Category:</strong>
  <%= @vendor.category %>
</p>

<p>
  <strong>Approved at:</strong>
  <%= @vendor.approved_at %>
</p>

<p>
  <strong>Approved by:</strong>
  <%= @vendor.approved_by %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>
</div>