config/routes.rb
Rails.application.routes.draw do
  resources :bands
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  get '/cart/checkout' => 'cart#checkout', as: :checkout
  get '/cart/:id' => 'cart#add', as: :add_to_cart

  devise_for :users
  resources :vendors
  resources :events do 
    resources :show_times
    collection do
      get :past
      get :upcoming
      get :calendar
      get :attending
      get :all, action: :index
    end
  end
  resource :transaction

  get 'home' => 'home#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'videos' => 'home#videos'
  get 'fall' => 'home#fall'
  get 'loco' => 'home#loco'
  get 'mongo' => 'home#mongo'
  get 'donate' => 'home#donate'
  get 'info' => 'home#info'

  root 'home#index'

end

app/views/layouts/_main_video.html.erb
<div class="col-md-12 light padd shadow">
    <h1>Videos</h1>
    <div class="col-md-6">
        <div class="embed-responsive embed-responsive-16by9">
            <%= embed("https://www.youtube.com/watch?v=bpjPAd39HLU") %>
        </div>
        <hr>
        <div class="embed-responsive embed-responsive-16by9">
            <%= embed("https://www.youtube.com/watch?v=b4-4BPh0KVY") %>
        </div>
    </div>
    <div class="col-md-6">
        
        <div class="embed-responsive embed-responsive-16by9">
            <%= embed("https://www.youtube.com/watch?v=b4-4BPh0KVY") %>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", home_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path, class: "navbar-link" %></li>
        <li><%= link_to "Donate", donate_path, class: "navbar-link" %></li>
        <li><%= link_to "Info", info_path, class: "navbar-link" %></li>
        <li><%= link_to "Vendors", vendors_path, class: "navbar-link" %></li>
        <li><%= link_to "Videos", videos_path, class: "navbar-link" %></li>
        <li><%= link_to "Contact", contact_path, class: "navbar-link" %></li>
        <li><%= link_to "Events", events_path, class: "navbar-link" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Festivals <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Event.all.each do |event| %>
              <li><%= link_to event.name, event, class: "navbar-link" %></li>
            <% end %>
          </ul>
        </li>
        <% if user_signed_in? && current_user.admin? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ADMIN <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Bands", bands_path, class: "navbar-link" %></li>
            <li><%= link_to "Events", events_path, class: "navbar-link" %></li>
          </ul>
        </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to cart_path, class: "navbar-link"  do %>
              <span class='badge badge-success'> <%=total_qty ? total_qty : 0 %> </span> <i class="fa fa-shopping-cart fa-2x text-success" aria-hidden="true"></i>  <span class='label label-info'> <%= total_amount ? number_to_currency(total_amount) : number_to_currency(0) %></span>
            <% end %>
        </li>
        <li><%= link_to "Sign Up", new_user_registration_path if !user_signed_in? %></li>
        <li><%= link_to "Sign In", new_user_session_path if !user_signed_in? %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete if user_signed_in? %></li>
        <li><%= link_to "Check Out", checkout_path, class: "btn btn-success" if total_qty > 0 %></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>
<div class="container" id="main">
  <p class="text-info" id="notice"><strong><%= notice %></strong></p>
  <%= yield %>  
</div>

</body>
</html>